# Server
server.port=8080

# PostgreSQL — injected from docker-compose environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sentimentiq}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sentimentiq_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sentimentiq_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis — injected from docker-compose environment variables
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# JWT
app.jwt.secret=${APP_JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e5b09b1a287a6527f65bd0820}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

# ML Service
app.ml.service.url=${APP_ML_SERVICE_URL:http://localhost:8000}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
